[profile.default]
solc = "0.8.24"
evm_version = "cancun"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
]
remappings = [
  "ds-test/=../../node_modules/ds-test/src/",
  "forge-std/=../../node_modules/forge-std/src/",
  "@latticexyz/=../../node_modules/@latticexyz/",
  "@eveworld/=../../node_modules/@eveworld/",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.local]
# Local Anvil Instance
eth_rpc_url = "http://127.0.0.1:8545"

[profile.testnet]
# Public Testnet
eth_rpc_url = "https://sepolia.optimism.io"

[profile.redstone]
# Public Mainnet
eth_rpc_url = "https://rpc.redstonechain.com"
